name: CI

on: pull_request

jobs:

  lint:
    name: Lint check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Build the lib so lint can check types
      run: npm run build
    - name: Lint check
      run: npm run lint

  test-latest:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test with Angular@latest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Build the lib
      run: npm run build
    - name: Run unit tests
      run: npm run unit:${{ matrix.os }}
    - name: Run unit tests in private mode
      run: npm run unit:${{ matrix.os }}:private
    - name: Install matching webdriver version
      run: ./node_modules/.bin/webdriver-manager update --versions.chrome $(google-chrome --version | cut -f 3 -d ' ')
      if: matrix.os == 'ubuntu-latest'
    - name: Run general e2e tests
      run: npm run e2e:demo
      if: matrix.os == 'ubuntu-latest'
    - name: Run interoperability e2e tests
      run: npm run e2e:interoperability
      if: matrix.os == 'ubuntu-latest'

  test-minimum:

    name: Test with Angular@12.0.0 and minimum dependencies requirements
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Build the lib (with the current version, as it is what is published on npm)
      run: npm run build
    - name: Downgrade dependencies to minimal required version
      run: npm install typescript@4.2.3 tslib@2.1.0 rxjs@6.5.3 zone.js@0.11.4 @angular/common@12.0.0 @angular/compiler@12.0.0 @angular/core@12.0.0 @angular/platform-browser@12.0.0 @angular/platform-browser-dynamic@12.0.0 @angular/router@12.0.0 @angular/cli@12.0.0 @angular/compiler-cli@12.0.0 @angular-devkit/build-angular@12.0.0
      env:
        CI: true
    - name: Run unit tests
      run: npm run unit:ubuntu-latest
    - name: Run unit tests in private mode
      run: npm run unit:ubuntu-latest:private
    - name: Install matching webdriver version
      run: ./node_modules/.bin/webdriver-manager update --versions.chrome $(google-chrome --version | cut -f 3 -d ' ')
    - name: Run general e2e tests
      run: npm run e2e:demo
    - name: Run interoperability e2e tests
      run: npm run e2e:interoperability

  test-next:

    name: Test with Angular@next and RxJS 7
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Build the lib (with the current version, as it is what is published on npm)
      run: npm run build
    - name: Upgrade dependencies to newer versions
      run: npm install typescript@4.3 rxjs@7 @angular/common@next @angular/compiler@next @angular/core@next @angular/platform-browser@next @angular/platform-browser-dynamic@next @angular/router@next @angular/cli@next @angular/compiler-cli@next @angular-devkit/build-angular@next --force
      env:
        CI: true
    - name: Run unit tests
      run: npm run unit:ubuntu-latest
    - name: Run unit tests in private mode
      run: npm run unit:ubuntu-latest:private
    - name: Install matching webdriver version
      run: ./node_modules/.bin/webdriver-manager update --versions.chrome $(google-chrome --version | cut -f 3 -d ' ')
    - name: Run general e2e tests
      run: npm run e2e:demo

